server:
  port: 80

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/jooq?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root


# 配置日志地址
logging:
  config: classpath:logback-spring.xml