server:
  port: 80

spring:
  #  profiles:
  #    include:
  #      - dynamic-tp
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # 解决springboot高版本Knife4j报错问题

# 配置日志地址
logging:
  config: classpath:logback-spring.xml