server:
  port: 80

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/querydsl?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root

  jpa:
    show-sql: true # 控制台打印SQL
    hibernate:
      ddl-auto: update

# 配置日志地址
logging:
  config: classpath:logback-spring.xml